# Generated by Django 5.1.1 on 2024-09-08 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bookmodel_categoriesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='categoriesmodel',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='categoriesmodel',
            name='book',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.categoriesmodel'),
            preserve_default=False,
        ),
    ]
