# Generated by Django 5.1.1 on 2024-09-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_bookmodel_category_bookmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='categoriesmodel',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.bookmodel'),
            preserve_default=False,
        ),
    ]
