# Generated by Django 5.1.1 on 2024-09-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_bookmodel_category_categoriesmodel_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesmodel',
            name='book',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='item', to='app.categoriesmodel'),
        ),
    ]
