# Generated by Django 5.1.1 on 2024-09-08 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_categoriesmodel_book_bookmodel_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='categoriesmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.categoriesmodel'),
        ),
        migrations.AddField(
            model_name='categoriesmodel',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
